name: Publish Postgres.js

permissions: {}

on:
  workflow_dispatch:
  push:
    tags:
      - "node/postgres-js/v*"

defaults:
  run:
    working-directory: node/postgres-js

jobs:
  wait-for-ci:
    name: Wait for CI to pass
    runs-on: ubuntu-latest
    steps:
      - uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: "Wait for CI to pass"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

  publish:
    needs: wait-for-ci
    runs-on: ubuntu-latest
    environment: NPM
    permissions:
      id-token: write # required for trusted publishing
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "25"
          registry-url: "https://registry.npmjs.org"

      - run: |
          npm ci
          npm run build:prod

      - run: npm publish --provenance

  update-changelog:
    name: Update changelog
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: node/postgres-js/CHANGELOG.md
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request: true
          version: ${{ github.ref_name }}
          args: -e ^node/postgres-js/
